language: javascript

env:
  global:
  - GH_REF: github.com/ColinLeverger/solar-system-webgl.git

script:
  - ls
  - echo "Replace these two lines with something more usefull, like tests or something..."

after_success:
  - bash ./deploy.sh